#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Creating Routes

category_list:
  path: /api/v1/categories
  controller: App\Controller\CategoryController:indexAction
  methods: [GET]

category_create:
  path: /api/v1/categories
  controller: App\Controller\CategoryController:createAction
  methods: [POST]

product_list:
  path: /api/v1/products
  controller: App\Controller\ProductController:indexAction
  methods: [GET]

product_create:
  path: /api/v1/products
  controller: App\Controller\ProductController:createAction
  methods: [POST]
